name: TNTRun
main: tntrun.TNTRun
depend: [WorldEdit]
softdepend: [Vault]
version: 6.0.9
author: [_Shevchik_, The_TadeSK]
commands:
  tntrunsetup:
    description: TNTRun arena setup commands
    aliases: trsetup
  tntrun:
    description: TNTRun game commands
    aliases: tr
  tntrunconsole:
    description: TNTRun console commands
    aliases: trconsole